### ISSUE TITLE
Error after finishing the Learning process

### ISSUE THREAD

**Issue by alexx-ftw** [AechPro/rlgym-ppo#1]
I am getting this error once the Learning process finishes:
```ERROR IN BATCHED AGENT LOOP
Traceback (most recent call last):
  File "c:\Users\x\Desktop\GetEmRLGym\venv\lib\site-packages\rlgym_ppo\batched_agents\batched_agent.py", line 43, in batched_agent_process
    pipe.send(("env_step_data", (obs, rew, done)))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 295, in _send_bytes
    nwritten, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] Ha terminado la canalización 
Failed to send stop signal to child process!```
```
It repeats many times. I guess once for each subprocess.

Doesn't seem to affect anything tho.

**Comment by alexx-ftw** [comment]
Closing as normal behaviour
