### ISSUE TITLE
Render error

### ISSUE THREAD

**Issue by alexx-ftw** [AechPro/rlgym-ppo#3]
Getting this error:
```
Traceback (most recent call last):
  File "C:\Users\x\Desktop\BrutusRL\.venv\lib\site-packages\rlgym_ppo\batched_agents\batched_agent.py", line 45, in batched_agent_process
    env.render()
  File "C:\Users\x\Desktop\BrutusRL\.venv\lib\site-packages\rlgym_sim\gym.py", line 91, in render
    rlviser.render_rlgym(self._prev_state)
TypeError: render_rlgym() missing 2 required positional arguments: 'tick_rate' and 'gym_state'
```

**Comment by AechPro** [comment]
rlviser and rlgym-sim were both recently updated. Make sure you have the latest rlviser binaries and the latest rlgym-sim version.

**Comment by alexx-ftw** [comment]
Still getting the error

**Comment by alexx-ftw** [comment]
Somehow fixed by itself after rebooting computer
